<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ActivityLog;
use App\Models\User;
use Carbon\Carbon;

class ActivityLogSeeder extends Seeder
{
    public function run(): void
    {
        // NOTE: Sample data seeding has been removed to prevent "admin@jetlouge.com" creation.
        // Real activity logs will be generated by system usage.
    }
}
