<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DestinationMasterSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            [
                'destination_name' => 'Customer Service Excellence in Travel Operations',
                'details' => 'Intensive training on improving customer interaction, complaint handling, and satisfaction ratings',
                'objectives' => 'To enhance customer satisfaction and loyalty through effective service delivery',
                'duration' => '3 days',
                'delivery_mode' => 'Workshop',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Sales and Marketing Strategies for Travel Packages',
                'details' => 'Create compelling marketing materials and sales techniques for domestic and international tours',
                'objectives' => 'To increase sales performance and develop competitive marketing strategies',
                'duration' => '5 days',
                'delivery_mode' => 'Workshop',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Sustainable Tourism Management and Product Development',
                'details' => 'Training on planning, organizing, and managing sustainable tourism products',
                'objectives' => 'To promote environmental sustainability and create unique tour packages',
                'duration' => '3 days',
                'delivery_mode' => 'On-Site Training',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Sustainable and Eco-Tourism Practices',
                'details' => 'Focus on sustainability and eco-friendly travel operations, and responsible tourism',
                'objectives' => 'To promote environmental responsibility and sustainable tourism practices',
                'duration' => '2 days',
                'delivery_mode' => 'Seminar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Corporate Travel Management Systems',
                'details' => 'Orientation on handling corporate travel accounts, business trip planning, and budget monitoring',
                'objectives' => 'To develop efficient systems for managing corporate travel accounts',
                'duration' => '2 days',
                'delivery_mode' => 'Blended Learning',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Airline and Ticketing Operations for Travel and Tourism Systems',
                'details' => 'Technical training on global distribution systems for ticketing, fares, and routing',
                'objectives' => 'To equip staff with ticketing and fare management skills',
                'duration' => '1 week',
                'delivery_mode' => 'Workshop',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Crisis Management and Emergency Preparedness in Tourism',
                'details' => 'Prepare staff to handle emergencies, crises, and unexpected events',
                'objectives' => 'To ensure staff readiness in handling crisis situations',
                'duration' => '3 days',
                'delivery_mode' => 'Table Training',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Hospitality and Guest Relations Management',
                'details' => 'Training on professional guest etiquette, courtesy, and guest handling techniques',
                'objectives' => 'To improve guest experience and satisfaction',
                'duration' => '2 days',
                'delivery_mode' => 'Seminar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Digital Marketing and Social Media for Travel Agencies',
                'details' => 'Utilize social media platforms, SEO, and online advertising for travel agencies',
                'objectives' => 'To leverage digital platforms to attract more clients',
                'duration' => '2 days',
                'delivery_mode' => 'Blended Learning',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Tour Guiding and Destination Management Systems',
                'details' => 'Develop skills in tour guiding, storytelling, and destination knowledge',
                'objectives' => 'To enhance tour guide skills and destination expertise',
                'duration' => '2 days',
                'delivery_mode' => 'Workshop',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Itinerary Development for Travel Agencies',
                'details' => 'Create well-balanced, engaging, and cost-effective itineraries',
                'objectives' => 'To develop compelling and cost-effective travel itineraries',
                'duration' => '3 days',
                'delivery_mode' => 'Table Training',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Travel Documentation and Visa Processing Compliance',
                'details' => 'Guide on handling international travel documents, visa applications, and embassy coordination procedures',
                'objectives' => 'To process travel documents efficiently',
                'duration' => '2 days',
                'delivery_mode' => 'On-Site Training',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Revenue and Yield Management and Global Etiquette',
                'details' => 'Focuses on handling international clients and understanding cultural differences',
                'objectives' => 'To develop cultural sensitivity and boost revenue profitability',
                'duration' => '1 week',
                'delivery_mode' => 'Seminar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Group Travel Operations and Coordination',
                'details' => 'Manage group bookings, group itineraries, and group coordination in diversity',
                'objectives' => 'To efficiently manage group travel operations and ensure efficiency',
                'duration' => '1 week',
                'delivery_mode' => 'On-Site Training',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Leadership and Team-Building for Travel Coordinators',
                'details' => 'Activities and exercises that develop leadership and collaborative relationships',
                'objectives' => 'To build teamwork, motivation, and leadership among staff',
                'duration' => '2 days',
                'delivery_mode' => 'Table Training',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Tourism Budgeting and Financial Management for Travel Agencies',
                'details' => 'Develop skills in budgeting, pricing, and cost-accounting',
                'objectives' => 'To boost financial literacy and profitability',
                'duration' => '3 days',
                'delivery_mode' => 'Seminar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Event and Tour Coordination Skills for Travel Agencies',
                'details' => 'Technical training in managing large-scale tours, tours, and conventions',
                'objectives' => 'To boost coordination and planning skills for large events',
                'duration' => '2 days',
                'delivery_mode' => 'Workshop',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Safety, Security, and Emergency Procedures in Tourism',
                'details' => 'Create safety protocols, first aid, and emergency response',
                'objectives' => 'To equip staffs with risk prevention and emergency response skills',
                'duration' => '2 days',
                'delivery_mode' => 'On-Site Training',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Quality Service Standards and Client Feedback Analysis',
                'details' => 'Manage on monitoring service quality frameworks and client feedback systems',
                'objectives' => 'To establish consistent service standards and continuous improvement',
                'duration' => '2 days',
                'delivery_mode' => 'Seminar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_name' => 'Environmental Sustainability and Corporate Social Responsibility in Travel',
                'details' => 'Training on integrating sustainability and social responsibility into travel operations',
                'objectives' => 'To promote sustainable practices and social impact in tourism',
                'duration' => '2 days',
                'delivery_mode' => 'Workshop',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        // Clear existing data first to avoid duplicates
        DB::table('destination_masters')->truncate();
        
        // Insert all destinations
        DB::table('destination_masters')->insert($destinations);
    }
}
